"use client";
import { useState, type ReactNode } from "react";
import { AlertCircle, BookOpen, Check, LoaderCircle, Search } from "lucide-react";
import type { NormalizedResource } from "~/server/discovery/normalization";

type StoredResource = Omit<NormalizedResource, "retrievedAt"> & { id: string; retrievedAt: Date | null };
type Association = { association: { id: string; relevanceReason: string | null; relevanceScore: number | null; selectedForRrl: boolean }; resource: StoredResource };
type Warning = { provider: string; code: string; message: string; retryable: boolean };
const providerName = (value: string) => ({ openalex: "OpenAlex", crossref: "Crossref", google_books: "Google Books" })[value] ?? value;

export function LiteratureWorkspace({ study, initialQueries, initialAssociated }: { study: { id: string; title: string }; initialQueries: string[]; initialAssociated: Association[] }) {
  const [query, setQuery] = useState(initialQueries[0] ?? ""), [results, setResults] = useState<NormalizedResource[]>([]), [associated, setAssociated] = useState(initialAssociated);
  const [warnings, setWarnings] = useState<Warning[]>([]), [loading, setLoading] = useState(false), [searched, setSearched] = useState(false), [message, setMessage] = useState("");
  const endpoint = `/api/studies/${study.id}/literature`;
  async function search() {
    setLoading(true); setMessage(""); setWarnings([]); setSearched(true);
    try { const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "search", query }) }); const body = await response.json() as { items?: NormalizedResource[]; warnings?: Warning[]; error?: string }; if (!response.ok) throw new Error(body.error ?? "Search failed."); setResults(body.items ?? []); setWarnings(body.warnings ?? []); }
    catch (e) { setResults([]); setMessage(e instanceof Error ? e.message : "Search failed."); } finally { setLoading(false); }
  }
  async function associate(resource: NormalizedResource) {
    const providerIdentifier = resource.source === "crossref" ? resource.doi : resource.sourceIdentifier;
    if (!providerIdentifier || resource.source === "manual") { setMessage("This result has no stable provider identity."); return; }
    setMessage("Associating authoritative provider record…");
    try { const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "associate", locator: { provider: resource.source, providerIdentifier } }) }); const body = await response.json() as { association?: Association["association"]; resource?: Association["resource"]; relevanceUnavailable?: boolean; error?: string }; if (!response.ok || !body.association || !body.resource) throw new Error(body.error ?? "Could not associate source."); setAssociated((current) => [{ association: body.association!, resource: body.resource! }, ...current.filter((item) => item.association.id !== body.association!.id)]); setMessage(body.relevanceUnavailable ? "Source associated. AI relevance explanation is unavailable; bibliographic metadata was preserved." : "Source associated with this Study."); }
    catch (e) { setMessage(e instanceof Error ? e.message : "Could not associate source."); }
  }
  async function select(id: string, selected: boolean) {
    try { const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "select", associationId: id, selected }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Selection failed."); setAssociated((current) => current.map((item) => item.association.id === id ? { ...item, association: { ...item.association, selectedForRrl: selected } } : item)); }
    catch (e) { setMessage(e instanceof Error ? e.message : "Selection could not be updated."); }
  }
  return <section className="mt-7 space-y-7">
    <header><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Related literature</p><h2 className="mt-2 text-2xl font-bold">{study.title}</h2><p className="mt-2 text-sm text-muted-foreground">Search concepts come from the saved Study Profile. Editing them here does not alter the Profile.</p></header>
    <form className="rounded-2xl border border-border bg-card p-5 shadow-sm" onSubmit={(e) => { e.preventDefault(); void search(); }}><label htmlFor="literature-query" className="text-sm font-semibold">Scholarly search query</label><div className="mt-2 flex flex-col gap-3 sm:flex-row"><input id="literature-query" value={query} maxLength={300} onChange={(e) => setQuery(e.target.value)} className="min-h-12 min-w-0 flex-1 rounded-xl border border-input bg-background px-3" /><button disabled={loading} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary px-5 font-semibold text-primary-foreground disabled:opacity-60">{loading ? <LoaderCircle className="size-4 animate-spin" /> : <Search className="size-4" />}{loading ? "Searching…" : "Search"}</button></div><div className="mt-3 flex flex-wrap gap-2">{initialQueries.map((q) => <button type="button" key={q} onClick={() => setQuery(q)} className="rounded-full border border-border px-3 py-1 text-left text-xs hover:bg-muted">{q}</button>)}<button type="button" onClick={() => setQuery(initialQueries[0] ?? "")} className="rounded-full px-3 py-1 text-xs font-semibold text-primary">Reset</button></div></form>
    {message && <p role="status" className="rounded-xl border border-border bg-muted/50 p-4 text-sm">{message}</p>}
    {!!warnings.length && <div role="alert" className="rounded-2xl border border-amber-500/40 bg-amber-500/5 p-5"><h3 className="flex items-center gap-2 font-semibold"><AlertCircle className="size-4" />Partial provider results</h3>{warnings.map((w) => <p key={`${w.provider}-${w.code}`} className="mt-2 text-sm">{providerName(w.provider)}: {w.message}</p>)}</div>}
    {!loading && searched && !results.length && <div className="rounded-2xl border border-dashed border-border p-10 text-center"><BookOpen className="mx-auto size-8 text-muted-foreground" /><h3 className="mt-3 font-semibold">No matching sources found</h3><p className="mt-1 text-sm text-muted-foreground">No real provider records matched “{query}”. Edit the query and search again.</p><button onClick={() => void search()} className="mt-4 rounded-xl border border-border px-4 py-2 text-sm font-semibold">Retry search</button></div>}
    {!!results.length && <div className="space-y-4"><h3 className="font-semibold">Discovered results</h3>{results.map((r, i) => <SourceCard key={`${r.source}-${r.sourceIdentifier}-${i}`} resource={r} action={<button onClick={() => void associate(r)} className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Associate with Study</button>} />)}</div>}
    <div className="space-y-4"><h3 className="text-lg font-semibold">Associated sources ({associated.length})</h3>{!associated.length && <p className="rounded-2xl border border-dashed border-border p-6 text-sm text-muted-foreground">No sources are associated with this Study yet.</p>}{associated.map((item) => <SourceCard key={item.association.id} resource={item.resource} association={item.association} action={<button onClick={() => void select(item.association.id, !item.association.selectedForRrl)} className={`inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold ${item.association.selectedForRrl ? "border-primary text-primary" : "border-border"}`}>{item.association.selectedForRrl && <Check className="size-4" />}{item.association.selectedForRrl ? "Selected for later RRL · Deselect" : "Select for later RRL"}</button>} />)}</div>
  </section>;
}

function SourceCard({ resource, association, action }: { resource: NormalizedResource | StoredResource; association?: Association["association"]; action: ReactNode }) {
  const provenance = Array.isArray(resource.citationMetadata?.provenance) ? resource.citationMetadata.provenance as Array<{ provider?: string }> : [];
  const extraProviders = provenance.map((p) => providerName(p.provider ?? "")).filter((v) => v && v !== providerName(resource.source));
  const context = resource.abstract ? (resource.type === "book" ? "Book description available" : "Title + abstract available") : resource.source === "crossref" ? "DOI metadata only" : "Title/bibliographic metadata only";
  return <article className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-primary/10 px-2.5 py-1 font-semibold text-primary">{resource.type}</span><span className="rounded-full bg-muted px-2.5 py-1">{providerName(resource.source)}{extraProviders.length ? ` + ${[...new Set(extraProviders)].join(" + ")}` : ""}</span><span className="rounded-full border border-border px-2.5 py-1">Context: {context}</span><span className="rounded-full border border-amber-500/40 px-2.5 py-1 text-amber-700 dark:text-amber-300">Integrity: Unknown / Not checked yet</span></div><h4 className="mt-3 text-lg font-semibold">{resource.title}</h4><p className="mt-1 text-sm text-muted-foreground">{resource.authors.length ? resource.authors.join(", ") : "Authors unavailable"}{resource.year ? ` · ${resource.year}` : ""}</p>{(resource.venue || resource.publisher) && <p className="mt-2 text-sm">{resource.venue ?? resource.publisher}</p>}{resource.doi && <p className="mt-2 break-all text-sm">DOI: {resource.doi}</p>}{resource.isbn && <p className="mt-1 text-sm">ISBN: {resource.isbn}</p>}{association && <div className="mt-4 rounded-xl bg-muted/50 p-4"><p className="text-xs font-bold uppercase tracking-wide">AI-generated relevance explanation</p><p className="mt-2 text-sm">{association.relevanceReason ?? "Relevance explanation unavailable."}</p>{association.relevanceScore !== null && <p className="mt-2 text-xs text-muted-foreground">Retrieval relevance: {Math.round(association.relevanceScore * 100)}% — not a quality or integrity score</p>}</div>}<div className="mt-4">{action}</div></article>;
}
