"use client";
import { useState, type ReactNode } from "react";
import { AlertCircle, BookOpen, Check, LoaderCircle, RefreshCw, Search, TriangleAlert } from "lucide-react";
import type { NormalizedResource } from "~/server/discovery/normalization";
import { formatPhilippineDateTime } from "~/lib/dates";
import { toast } from "sonner";
import { literatureEmptyState } from "./literature-search-state";

type StoredResource = Omit<NormalizedResource, "retrievedAt"> & { id: string; retrievedAt: Date | null };
type Integrity = { status: "no_known_issue" | "review_required" | "corrected" | "retracted" | "unknown"; doiVerified: boolean | null; updateType: string | null; updateDoi: string | null; updateLabel: string | null; integritySource: string | null; metadataComplete: boolean | null; checkedAt: string | Date; rawMetadataHash?: string | null; stale?: boolean; refreshError?: string | null };
type IntegrityResult = { check: Integrity | null; stale: boolean; refreshError: string | null; reused: boolean };
type Association = { association: { id: string; relevanceReason: string | null; relevanceScore: number | null; selectedForRrl: boolean }; resource: StoredResource; integrity: Integrity | null };
type Warning = { provider: string; code: string; message: string; retryable: boolean };
const providerName = (value: string) => ({ openalex: "OpenAlex", crossref: "Crossref", google_books: "Google Books" })[value] ?? value;

export function LiteratureWorkspace({ study, initialQueries, initialAssociated }: { study: { id: string; title: string }; initialQueries: string[]; initialAssociated: Association[] }) {
  const [query, setQuery] = useState(initialQueries[0] ?? ""), [results, setResults] = useState<NormalizedResource[]>([]), [associated, setAssociated] = useState(initialAssociated);
  const [warnings, setWarnings] = useState<Warning[]>([]), [loading, setLoading] = useState(false), [busy, setBusy] = useState(false), [searched, setSearched] = useState(false), [requestFailed, setRequestFailed] = useState(false);
  const emptyState = literatureEmptyState(searched, loading, results.length, warnings.length, requestFailed);
  const endpoint = `/api/studies/${study.id}/literature`;
  async function search() {
    setLoading(true); setWarnings([]); setRequestFailed(false); setSearched(true);
    try { const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "search", query }) }); const body = await response.json() as { items?: NormalizedResource[]; warnings?: Warning[]; error?: string }; if (!response.ok) throw new Error(body.error ?? "Search failed."); setResults(body.items ?? []); setWarnings(body.warnings ?? []); }
    catch (e) { const message = e instanceof Error ? e.message : "Search failed."; setResults([]); setRequestFailed(true); toast.error(message); } finally { setLoading(false); }
  }
  async function associate(resource: NormalizedResource) {
    const providerIdentifier = resource.source === "crossref" ? resource.doi : resource.sourceIdentifier;
    if (!providerIdentifier || resource.source === "manual") { toast.error("This result has no stable provider identity."); return; }
    setBusy(true);
    try { const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "associate", locator: { provider: resource.source, providerIdentifier } }) }); const body = await response.json() as { association?: Association["association"]; resource?: Association["resource"]; relevanceUnavailable?: boolean; error?: string }; if (!response.ok || !body.association || !body.resource) throw new Error(body.error ?? "Could not associate source."); setAssociated((current) => [{ association: body.association!, resource: body.resource!, integrity: null }, ...current.filter((item) => item.association.id !== body.association!.id)]); toast.success("Source associated with this study."); if (body.relevanceUnavailable) toast.warning("AI relevance explanation is unavailable; bibliographic metadata was preserved."); }
    catch (e) { toast.error(e instanceof Error ? e.message : "Could not associate source."); } finally { setBusy(false); }
  }
  async function select(id: string, selected: boolean) {
    setBusy(true);
    try { const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "select", associationId: id, selected }) }); const body = await response.json() as { association?: Association["association"]; integrity?: IntegrityResult | null; error?: string }; if (!response.ok || !body.association) throw new Error(body.error ?? "Selection failed."); setAssociated((current) => current.map((item) => item.association.id === id ? { ...item, association: body.association!, integrity: body.integrity?.check ? { ...body.integrity.check, stale: body.integrity.stale, refreshError: body.integrity.refreshError } : item.integrity } : item)); toast.success(selected ? "Source selected for RRL." : "Source removed from RRL selection."); }
    catch (e) { toast.error(e instanceof Error ? e.message : "Selection could not be updated."); } finally { setBusy(false); }
  }
  async function refreshIntegrity(id: string) {
    setBusy(true);
    try { const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "refreshIntegrity", associationId: id }) }); const body = await response.json() as { integrity?: IntegrityResult; error?: string }; if (!response.ok || !body.integrity) throw new Error(body.error ?? "Integrity refresh failed."); setAssociated((current) => current.map((item) => item.association.id === id ? { ...item, integrity: body.integrity!.check ? { ...body.integrity!.check, stale: body.integrity!.stale, refreshError: body.integrity!.refreshError } : item.integrity } : item)); if (body.integrity.refreshError) toast.error(body.integrity.refreshError); else toast.success("Source health refreshed."); }
    catch (e) { toast.error(e instanceof Error ? e.message : "Integrity refresh failed."); } finally { setBusy(false); }
  }
  return <section className="mt-7 space-y-7">
    <header><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Related literature</p><h2 className="mt-2 text-2xl font-bold">{study.title}</h2><p className="mt-2 text-sm text-muted-foreground">Search concepts come from the saved Study Profile. Editing them here does not alter the Profile.</p></header>
    <form className="rounded-2xl border border-border bg-card p-5 shadow-sm" onSubmit={(e) => { e.preventDefault(); void search(); }}><label htmlFor="literature-query" className="text-sm font-semibold">Scholarly search query</label><div className="mt-2 flex flex-col gap-3 sm:flex-row"><input id="literature-query" value={query} maxLength={300} onChange={(e) => setQuery(e.target.value)} className="min-h-12 min-w-0 flex-1 rounded-xl border border-input bg-background px-3" /><button disabled={loading} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary px-5 font-semibold text-primary-foreground disabled:opacity-60">{loading ? <LoaderCircle className="size-4 animate-spin" /> : <Search className="size-4" />}{loading ? "Searching…" : "Search"}</button></div><div className="mt-3 flex flex-wrap gap-2">{initialQueries.map((q) => <button type="button" key={q} onClick={() => setQuery(q)} className="rounded-full border border-border px-3 py-1 text-left text-xs hover:bg-muted">{q}</button>)}<button type="button" onClick={() => setQuery(initialQueries[0] ?? "")} className="rounded-full px-3 py-1 text-xs font-semibold text-primary">Reset</button></div></form>
    {!!warnings.length && <div role="alert" className="rounded-2xl border border-amber-500/40 bg-amber-500/5 p-5"><h3 className="flex items-center gap-2 font-semibold"><AlertCircle className="size-4" />{results.length ? "Partial provider results" : "Search provider unavailable"}</h3>{warnings.map((w) => <p key={`${w.provider}-${w.code}`} className="mt-2 text-sm">{providerName(w.provider)}: {w.message}</p>)}</div>}
    {emptyState === "unavailable" && <div role="alert" className="rounded-2xl border border-dashed border-amber-500/40 bg-amber-500/5 p-10 text-center"><AlertCircle className="mx-auto size-8 text-amber-600 dark:text-amber-400" /><h3 className="mt-3 font-semibold">Literature search unavailable</h3><p className="mt-1 text-sm text-muted-foreground">The search could not confirm whether sources match “{query}”. Try again shortly.</p><button onClick={() => void search()} className="mt-4 rounded-xl border border-border px-4 py-2 text-sm font-semibold">Retry search</button></div>}
    {emptyState === "no_matches" && <div className="rounded-2xl border border-dashed border-border p-10 text-center"><BookOpen className="mx-auto size-8 text-muted-foreground" /><h3 className="mt-3 font-semibold">No matching sources found</h3><p className="mt-1 text-sm text-muted-foreground">No real provider records matched “{query}”. Edit the query and search again.</p><button onClick={() => void search()} className="mt-4 rounded-xl border border-border px-4 py-2 text-sm font-semibold">Retry search</button></div>}
    {!!results.length && <div className="space-y-4"><h3 className="font-semibold">Discovered results</h3>{results.map((r, i) => <SourceCard key={`${r.source}-${r.sourceIdentifier}-${i}`} resource={r} action={<button disabled={busy} onClick={() => void associate(r)} className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-60">{busy ? "Working…" : "Associate with Study"}</button>} />)}</div>}
    <div className="space-y-4"><h3 className="text-lg font-semibold">Associated sources ({associated.length})</h3>{!associated.length && <p className="rounded-2xl border border-dashed border-border p-6 text-sm text-muted-foreground">No sources are associated with this Study yet.</p>}{associated.map((item) => <SourceCard key={item.association.id} resource={item.resource} association={item.association} integrity={item.integrity} action={<><button disabled={busy} onClick={() => void select(item.association.id, !item.association.selectedForRrl)} className={`inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold disabled:opacity-60 ${item.association.selectedForRrl ? "border-primary text-primary" : "border-border"}`}>{item.association.selectedForRrl && <Check className="size-4" />}{item.association.selectedForRrl ? "Selected for later RRL · Deselect" : "Select for later RRL"}</button><button disabled={busy} onClick={() => void refreshIntegrity(item.association.id)} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-sm font-semibold disabled:opacity-60"><RefreshCw className="size-4" />{busy ? "Refreshing…" : "Refresh health"}</button></>} />)}</div>
  </section>;
}

function SourceCard({ resource, association, integrity, action }: { resource: NormalizedResource | StoredResource; association?: Association["association"]; integrity?: Integrity | null; action: ReactNode }) {
  const provenance = Array.isArray(resource.citationMetadata?.provenance) ? resource.citationMetadata.provenance as Array<{ provider?: string }> : [];
  const extraProviders = provenance.map((p) => providerName(p.provider ?? "")).filter((v) => v && v !== providerName(resource.source));
  const context = resource.abstract ? (resource.type === "book" ? "Book description available" : "Title + abstract available") : resource.source === "crossref" ? "DOI metadata only" : "Title/bibliographic metadata only";
  return <article className="rounded-2xl border border-border bg-card p-5 shadow-sm">{integrity?.status === "retracted" && <div role="alert" className="mb-4 rounded-xl border-2 border-red-600 bg-red-500/10 p-4 font-semibold text-red-800 dark:text-red-200"><TriangleAlert className="mr-2 inline size-5" />Retracted — review before use</div>}<div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-primary/10 px-2.5 py-1 font-semibold text-primary">{resource.type}</span><span className="rounded-full bg-muted px-2.5 py-1">{providerName(resource.source)}{extraProviders.length ? ` + ${[...new Set(extraProviders)].join(" + ")}` : ""}</span><span className="rounded-full border border-border px-2.5 py-1">Context: {context}</span></div><h4 className="mt-3 text-lg font-semibold">{resource.title}</h4><p className="mt-1 text-sm text-muted-foreground">{resource.authors.length ? resource.authors.join(", ") : "Authors unavailable"}{resource.year ? ` · ${resource.year}` : ""}</p>{(resource.venue || resource.publisher) && <p className="mt-2 text-sm">{resource.venue ?? resource.publisher}</p>}{resource.doi && <p className="mt-2 break-all text-sm">DOI: {resource.doi}</p>}{resource.isbn && <p className="mt-1 text-sm">ISBN: {resource.isbn}</p>}{association && <><SourceHealth resource={resource} integrity={integrity} /><div className="mt-4 rounded-xl bg-muted/50 p-4"><p className="text-xs font-bold uppercase tracking-wide">AI-generated relevance explanation</p><p className="mt-2 text-sm">{association.relevanceReason ?? "Relevance explanation unavailable."}</p>{association.relevanceScore !== null && <p className="mt-2 text-xs text-muted-foreground">Retrieval relevance: {Math.round(association.relevanceScore * 100)}% — not a quality or integrity score</p>}</div></>}<div className="mt-4 flex flex-wrap gap-2">{action}</div></article>;
}

function SourceHealth({ resource, integrity }: { resource: NormalizedResource | StoredResource; integrity?: Integrity | null }) {
  const status = integrity?.status ?? "unknown";
  const labels = { no_known_issue: "No known metadata issue found", review_required: "Review required", corrected: "Corrected / update recorded", retracted: "Retracted", unknown: "Integrity not checked / unavailable" };
  const styles = { no_known_issue: "border-sky-500/40 bg-sky-500/5", review_required: "border-amber-500/40 bg-amber-500/5", corrected: "border-amber-500/40 bg-amber-500/5", retracted: "border-red-600 bg-red-500/10", unknown: "border-border bg-muted/40" };
  const doiLabel = integrity?.doiVerified === true ? "Verified" : integrity?.doiVerified === false ? "Not verified" : "Unavailable / unknown";
  const checked = integrity?.checkedAt ? formatPhilippineDateTime(integrity.checkedAt) : "Not checked";
  const evidenceUrl = integrity?.updateDoi ? `https://doi.org/${encodeURIComponent(integrity.updateDoi)}` : resource.doi ? `https://doi.org/${encodeURIComponent(resource.doi)}` : null;
  return <section className={`mt-4 rounded-xl border p-4 text-sm ${styles[status]}`} aria-label="Source Health"><p className="text-xs font-bold uppercase tracking-wide">Source Health</p><p className="mt-2 font-semibold">DOI: {doiLabel}</p><p className="font-semibold">Integrity: {labels[status]}</p>{integrity?.stale && <p className="mt-2 font-semibold">Last known result is stale; refresh failed. {integrity.refreshError}</p>}{status === "no_known_issue" && <p className="mt-2 text-muted-foreground">No correction, retraction, or configured warning was found in the metadata checked at this time. This does not verify scientific quality or correctness.</p>}{status === "unknown" && <p className="mt-2 text-muted-foreground">{integrity?.updateLabel ?? (resource.doi ? "Check this DOI to retrieve Crossref metadata." : "No DOI is available for this source, so Crossref integrity metadata could not be checked.")}</p>}{(status === "corrected" || status === "review_required" || status === "retracted") && <p className="mt-2">{integrity?.updateLabel ?? "Crossref update metadata requires review."}</p>}<p className="mt-2 text-xs text-muted-foreground">Source: {integrity?.integritySource === "crossref" ? "Crossref metadata" : integrity ? "Integrity provider unavailable or not applicable" : "Not checked"} · Metadata completeness: {integrity?.metadataComplete === true ? "Complete" : integrity?.metadataComplete === false ? "Incomplete" : "Unknown"} · Last checked: {checked}</p>{evidenceUrl && <a className="mt-2 inline-block text-xs font-semibold text-primary underline" href={evidenceUrl} target="_blank" rel="noreferrer">View DOI evidence</a>}</section>;
}
